package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"

	"github.com/aashiq-04/oracle-dba/internal/graph/model"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	panic(fmt.Errorf("not implemented: Logout - logout"))
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	panic(fmt.Errorf("not implemented: CreateUser - createUser"))
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input model.UpdateUserInput) (*model.User, error) {
	panic(fmt.Errorf("not implemented: UpdateUser - updateUser"))
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, userID string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteUser - deleteUser"))
}

// AssignRole is the resolver for the assignRole field.
func (r *mutationResolver) AssignRole(ctx context.Context, userID string, roleID string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: AssignRole - assignRole"))
}

// RevokeRole is the resolver for the revokeRole field.
func (r *mutationResolver) RevokeRole(ctx context.Context, userID string, roleID string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: RevokeRole - revokeRole"))
}

// KillSession is the resolver for the killSession field.
func (r *mutationResolver) KillSession(ctx context.Context, sid int, serial int) (bool, error) {
	panic(fmt.Errorf("not implemented: KillSession - killSession"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Roles is the resolver for the roles field.
func (r *queryResolver) Roles(ctx context.Context) ([]*model.Role, error) {
	panic(fmt.Errorf("not implemented: Roles - roles"))
}

// Permissions is the resolver for the permissions field.
func (r *queryResolver) Permissions(ctx context.Context) ([]*model.Permission, error) {
	panic(fmt.Errorf("not implemented: Permissions - permissions"))
}

// Sessions is the resolver for the sessions field.
func (r *queryResolver) Sessions(ctx context.Context, filter *model.SessionFilterInput) ([]*model.OracleSession, error) {
	panic(fmt.Errorf("not implemented: Sessions - sessions"))
}

// ActiveSessions is the resolver for the activeSessions field.
func (r *queryResolver) ActiveSessions(ctx context.Context, filter *model.SessionFilterInput) ([]*model.OracleSession, error) {
	panic(fmt.Errorf("not implemented: ActiveSessions - activeSessions"))
}

// SessionSummary is the resolver for the sessionSummary field.
func (r *queryResolver) SessionSummary(ctx context.Context) (*model.SessionSummary, error) {
	panic(fmt.Errorf("not implemented: SessionSummary - sessionSummary"))
}

// Session is the resolver for the session field.
func (r *queryResolver) Session(ctx context.Context, sid int) (*model.OracleSession, error) {
	panic(fmt.Errorf("not implemented: Session - session"))
}

// BlockingSessions is the resolver for the blockingSessions field.
func (r *queryResolver) BlockingSessions(ctx context.Context) ([]*model.BlockingSession, error) {
	panic(fmt.Errorf("not implemented: BlockingSessions - blockingSessions"))
}

// Locks is the resolver for the locks field.
func (r *queryResolver) Locks(ctx context.Context, schemaName *string) ([]*model.LockInfo, error) {
	panic(fmt.Errorf("not implemented: Locks - locks"))
}

// Tablespaces is the resolver for the tablespaces field.
func (r *queryResolver) Tablespaces(ctx context.Context, filter *model.TablespaceFilterInput) ([]*model.Tablespace, error) {
	panic(fmt.Errorf("not implemented: Tablespaces - tablespaces"))
}

// Tablespace is the resolver for the tablespace field.
func (r *queryResolver) Tablespace(ctx context.Context, name string) (*model.Tablespace, error) {
	panic(fmt.Errorf("not implemented: Tablespace - tablespace"))
}

// TablespaceHistory is the resolver for the tablespaceHistory field.
func (r *queryResolver) TablespaceHistory(ctx context.Context, name string, timeRange model.TimeRangeInput) ([]*model.TablespaceMetric, error) {
	panic(fmt.Errorf("not implemented: TablespaceHistory - tablespaceHistory"))
}

// TablespaceGrowth is the resolver for the tablespaceGrowth field.
func (r *queryResolver) TablespaceGrowth(ctx context.Context, name string, days int) (*model.TablespaceGrowth, error) {
	panic(fmt.Errorf("not implemented: TablespaceGrowth - tablespaceGrowth"))
}

// TopSQLByElapsedTime is the resolver for the topSqlByElapsedTime field.
func (r *queryResolver) TopSQLByElapsedTime(ctx context.Context, limit int) ([]*model.SQLPerformance, error) {
	panic(fmt.Errorf("not implemented: TopSQLByElapsedTime - topSqlByElapsedTime"))
}

// TopSQLByCPUTime is the resolver for the topSqlByCpuTime field.
func (r *queryResolver) TopSQLByCPUTime(ctx context.Context, limit int) ([]*model.SQLPerformance, error) {
	panic(fmt.Errorf("not implemented: TopSQLByCPUTime - topSqlByCpuTime"))
}

// TopSQLByExecutions is the resolver for the topSqlByExecutions field.
func (r *queryResolver) TopSQLByExecutions(ctx context.Context, limit int) ([]*model.SQLPerformance, error) {
	panic(fmt.Errorf("not implemented: TopSQLByExecutions - topSqlByExecutions"))
}

// TopSQLByDiskReads is the resolver for the topSqlByDiskReads field.
func (r *queryResolver) TopSQLByDiskReads(ctx context.Context, limit int) ([]*model.SQLPerformance, error) {
	panic(fmt.Errorf("not implemented: TopSQLByDiskReads - topSqlByDiskReads"))
}

// SQLPerformance is the resolver for the sqlPerformance field.
func (r *queryResolver) SQLPerformance(ctx context.Context, filter *model.SQLPerformanceFilterInput) ([]*model.SQLPerformance, error) {
	panic(fmt.Errorf("not implemented: SQLPerformance - sqlPerformance"))
}

// SQLByID is the resolver for the sqlById field.
func (r *queryResolver) SQLByID(ctx context.Context, sqlID string) (*model.SQLPerformance, error) {
	panic(fmt.Errorf("not implemented: SQLByID - sqlById"))
}

// SQLHistory is the resolver for the sqlHistory field.
func (r *queryResolver) SQLHistory(ctx context.Context, sqlID string, timeRange model.TimeRangeInput) ([]*model.SQLMetric, error) {
	panic(fmt.Errorf("not implemented: SQLHistory - sqlHistory"))
}

// Schemas is the resolver for the schemas field.
func (r *queryResolver) Schemas(ctx context.Context) ([]*model.SchemaInfo, error) {
	panic(fmt.Errorf("not implemented: Schemas - schemas"))
}

// SchemaInfo is the resolver for the schemaInfo field.
func (r *queryResolver) SchemaInfo(ctx context.Context, name string) (*model.SchemaInfo, error) {
	panic(fmt.Errorf("not implemented: SchemaInfo - schemaInfo"))
}

// InvalidObjects is the resolver for the invalidObjects field.
func (r *queryResolver) InvalidObjects(ctx context.Context, schemaName *string) ([]*model.InvalidObject, error) {
	panic(fmt.Errorf("not implemented: InvalidObjects - invalidObjects"))
}

// RecentSchemaChanges is the resolver for the recentSchemaChanges field.
func (r *queryResolver) RecentSchemaChanges(ctx context.Context, schemaName *string, days int) ([]*model.SchemaChange, error) {
	panic(fmt.Errorf("not implemented: RecentSchemaChanges - recentSchemaChanges"))
}

// DatabaseInstance is the resolver for the databaseInstance field.
func (r *queryResolver) DatabaseInstance(ctx context.Context) (*model.DatabaseInstance, error) {
	panic(fmt.Errorf("not implemented: DatabaseInstance - databaseInstance"))
}

// DatabaseSize is the resolver for the databaseSize field.
func (r *queryResolver) DatabaseSize(ctx context.Context) (*model.DatabaseSize, error) {
	panic(fmt.Errorf("not implemented: DatabaseSize - databaseSize"))
}

// AuditLogs is the resolver for the auditLogs field.
func (r *queryResolver) AuditLogs(ctx context.Context, filter *model.AuditLogFilterInput, limit int, offset int) ([]*model.AuditLog, error) {
	panic(fmt.Errorf("not implemented: AuditLogs - auditLogs"))
}

// AuditLog is the resolver for the auditLog field.
func (r *queryResolver) AuditLog(ctx context.Context, id string) (*model.AuditLog, error) {
	panic(fmt.Errorf("not implemented: AuditLog - auditLog"))
}

// SessionAdded is the resolver for the sessionAdded field.
func (r *subscriptionResolver) SessionAdded(ctx context.Context) (<-chan *model.OracleSession, error) {
	panic(fmt.Errorf("not implemented: SessionAdded - sessionAdded"))
}

// BlockingDetected is the resolver for the blockingDetected field.
func (r *subscriptionResolver) BlockingDetected(ctx context.Context) (<-chan *model.BlockingSession, error) {
	panic(fmt.Errorf("not implemented: BlockingDetected - blockingDetected"))
}

// TablespaceAlert is the resolver for the tablespaceAlert field.
func (r *subscriptionResolver) TablespaceAlert(ctx context.Context, threshold float64) (<-chan *model.Tablespace, error) {
	panic(fmt.Errorf("not implemented: TablespaceAlert - tablespaceAlert"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
